### ISSUE TITLE
软件使用咨询

### ISSUE THREAD

**Issue by ModestYjx** [skycity233/SMPIC#1]
请问下载好安装包后，点击什么地方可以使用软件呢？

**Comment by realjackwang** [comment]
你下的应该是源码，我忘记上传EXE了，我做的不太好，
所以还是推荐使用PicGo哦 https://github.com/Molunerfinn/PicGo/releases/tag/v2.2.2
功能一样，但是更加的丰富

**Comment by ModestYjx** [comment]
非常感谢哥哥，多谢啦~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jack Wang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月8日(星期三) 上午9:49
收件人:&nbsp;"skycity233/SMPIC"<SMPIC@noreply.github.com&gt;;
抄送:&nbsp;"Modest❄"<929604665@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [skycity233/SMPIC] 软件使用咨询 (#1)





 
你下的应该是源码，我忘记上传EXE了，我做的不太好，
 所以还是推荐使用PicGo哦 https://github.com/Molunerfinn/PicGo/releases/tag/v2.2.2
 功能一样，但是更加的丰富

**Comment by ModestYjx** [comment]
老哥，再问一下，PicGo软件都不需要绑定smsm账号直接上传的嘛？我没有看到绑定的入口呀？另外，我试了一下PicGo为什么使用报错呢？报错截图在附件中，有空帮忙解答一下，非常感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jack Wang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月8日(星期三) 上午9:49
收件人:&nbsp;"skycity233/SMPIC"<SMPIC@noreply.github.com&gt;;
抄送:&nbsp;"Modest❄"<929604665@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [skycity233/SMPIC] 软件使用咨询 (#1)





 
你下的应该是源码，我忘记上传EXE了，我做的不太好，
 所以还是推荐使用PicGo哦 https://github.com/Molunerfinn/PicGo/releases/tag/v2.2.2
 功能一样，但是更加的丰富

**Comment by ModestYjx** [comment]
老哥，再多问一下：请问您有使用过mathpix这个数学公式识别软件吗？我用我的信用卡注册mathpix时，信用卡账号这一行一直现红，网站又不提示怎么修改这个错误？请问这是我的信用卡的问题呢，还是最近都注册不了嘞？
非常感谢！
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jack Wang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月8日(星期三) 上午9:49
收件人:&nbsp;"skycity233/SMPIC"<SMPIC@noreply.github.com&gt;;
抄送:&nbsp;"Modest❄"<929604665@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [skycity233/SMPIC] 软件使用咨询 (#1)





 
你下的应该是源码，我忘记上传EXE了，我做的不太好，
 所以还是推荐使用PicGo哦 https://github.com/Molunerfinn/PicGo/releases/tag/v2.2.2
 功能一样，但是更加的丰富

**Comment by ModestYjx** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jack Wang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月8日(星期三) 上午9:49
收件人:&nbsp;"skycity233/SMPIC"<SMPIC@noreply.github.com&gt;;
抄送:&nbsp;"Modest❄"<929604665@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [skycity233/SMPIC] 软件使用咨询 (#1)





 
你下的应该是源码，我忘记上传EXE了，我做的不太好，
 所以还是推荐使用PicGo哦 https://github.com/Molunerfinn/PicGo/releases/tag/v2.2.2
 功能一样，但是更加的丰富

**Comment by realjackwang** [comment]
附件？我没看到呀，你说的sm.ms登录问题，picgo是有这样的插件的，原生不支持登录，有插件可以实现，软件里面就可以下载插件

mathpix，我也有使用，不记得有注册这个步骤，我使用的是这个软件 mathpix snipping tool

**Comment by realjackwang** [comment]
更新后的确要登录了，不过只需要邮箱呀，在软件上就能注册，邮箱验证就ok了

**Comment by ModestYjx** [comment]
嗯嗯，谢谢您的帮助~
老哥您现在是读书还是工作了呢？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jack Wang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月10日(星期五) 中午1:16
收件人:&nbsp;"skycity233/SMPIC"<SMPIC@noreply.github.com&gt;;
抄送:&nbsp;"Modest❄"<929604665@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [skycity233/SMPIC] 软件使用咨询 (#1)





 
更新后的确要登录了，不过只需要邮箱呀，在软件上就能注册，邮箱验证就ok了

**Comment by realjackwang** [comment]
马上毕业了

**Comment by ModestYjx** [comment]
噢噢~我现在大三，准备保研嘞~------------------ 原始邮件 ------------------
发件人: "Jack Wang"<notifications@github.com>
发送时间: 2020年4月10日(星期五) 晚上8:05
收件人: "skycity233/SMPIC"<SMPIC@noreply.github.com>;
抄送: "ModestYjx"<929604665@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [skycity233/SMPIC] 软件使用咨询 (#1)




 
马上毕业了
 
&mdash;
